### ISSUE TITLE
Fixed calendar / user

### ISSUE THREAD

**Issue by hdijkema** [Offerel/roundcube_caldavzap#15]
Hi, 

I'm trying the caldavzap plugin. Need to fix the CORS problems, but I'll probably get that fixed.
However, I see that caldavzap tries to get a url postfixed with the roundcube username (or identity?).

What if I want to have a fixed caldav address per identity, or just one caldav address for all identities?

**Comment by Offerel** [comment]
This depends on the backend. At least with Baikal, SabreDAV you configure global calendars or shared calendars between accounts inside the backend itself. . NextCloud/Owncloud is based on SabreDAV, so you should ask there for support. If you use other backends, this can differ, you should ask the developer of this backend in this case.

And yes, for authentication at the backend, the username/password for Roundcube is used.

**Comment by hdijkema** [comment]
Oke...can I change that behaviour by pre-configuring my own username/passwords?

**Comment by Offerel** [comment]
You can try to fork the repository and change this behavior in the connector if you want. 

But for it didn't make sense, to not use the credentials from the logged in roundcube user. At least in my opinion, this would break user privacy/security, to use a hardcoded username/password. Since i didn't understand the use case for this, I have no idea what I should change, without to break the above mentioned things.

**Comment by hdijkema** [comment]
Okay,

I got it working as follows:

Given:

- my email address:  `myname@domain.my`
- my owncloud server at the internal address: `backend.mydomain.local`
- my family diary as user 'diary' in the owncloud server
- my owncloud server at the external address: `cloud.domain.my`
- my roundcube site at the external address: `mail.domain.my`

1. I created a new user `myname@domain.my` in my owncloud server as administrator in `cloud.domain.my`
2. I configured the new user to have the same password as the mail user in roundcube
2. I logged into the 'diary' account of my owncloud server and shared the calendar with `myname@domain.my`
3. In the apache configuration of my roundcube site I added:

```apache
    <IfModule mod_headers.c>
        Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
    </IfModule>

    ProxyPass "/remote.php/dav/calendars/" "http://backend.mydomain.local/remote.php/dav/calendars/"
    ProxyPassReverse "/remote.php/dav/calendars/" "http://backend.mydomain.local/remote.php/dav/calendars/"
```

And now it works.

**Comment by Offerel** [comment]
I have no idea, how database is setup for calendars in owncloud, but since its based on SabreDAV, you can share a calendar, when you create for example calendar "family" with user "firstuser". This will be the owner of the calendar:
```
INSERT INTO `main`.`calendarinstances` (`id`, `calendarid`, `principaluri`, `access`, `displayname`, `uri`, `description`, `calendarorder`, `calendarcolor`, `timezone`, `transparent`, `share_href`, `share_displayname`, `share_invitestatus`) VALUES ('11', '11', 'principals/firstuser@mydomain.com', '1', 'family', 'a085fe12-e854-4391-bda8-108a22cb2115', 'Family Calendar', '0', '#9446BAFF', 'Europe/Berlin', '0', '', '', '2');
```

To share this calendar with a seconduser, you can do:
```
INSERT INTO `main`.`calendarinstances` (`id`, `calendarid`, `principaluri`, `access`, `displayname`, `uri`, `description`, `calendarorder`, `calendarcolor`, `timezone`, `transparent`, `share_href`, `share_displayname`, `share_invitestatus`) VALUES ('12', '11', 'principals/seconduser@mydomain.com', '3', 'family', '10005b5a-df9b-48ba-9d5e-43b6d58f3945', 'Family Calendar', '0', '#9446BAFF', 'Europe/Berlin', '1', 'mailto:seconduser@mydomain.com', '', '2');
```

and in calendars:
```
INSERT INTO `main`.`calendars` (`id`, `synctoken`, `components`) VALUES ('11', '374', 'VEVENT');
```

If firstuser adds an event in calendar "family", seconduser can view, edit, change, delete this event, since its also available for him in his own instance of "family". The calendar is shared. All user, uses only a "virtual view" to this calendar. Works nicely here with pure SabreDAV. If this share calendar should also hold tasks, you should replace "VEVENT" with "VEVENT,VTODO". This works also in Baikal. Anyway, since you have found a solution, i close the issue.
