### ISSUE TITLE
This is a question not an issue

### ISSUE THREAD

**Issue by N0ury** [Offerel/roundcube_caldavzap#19]
Hi,

I'm currently using infcloud from [here](https://www.inf-it.com/open-source/clients/infcloud/)
Before that, I was using caldavzap + carddavzap.

I'm also moving (once again!) from rainloop to roundcube. This due to it's better supported GPG.
So I'm looking for a caldav plugin for roundcube.
I've found this project.

Is it possible to have some screenshots of roundcube_caldavzap?

Thanks

**Comment by Offerel** [comment]
I can try to make some at the weekend. It looks identical to CalDavZap. The only difference is that i have integrated the function buttons into the style of Roundcube. I have also changed the authentication, so that it uses the Roundcube credentials, so that you do not have to authenticate a second time.

**Comment by Offerel** [comment]
![Calendar Settings](https://user-images.githubusercontent.com/14041522/132008399-91c0df15-fe4c-4041-a41d-b7a20bbba564.jpg)
![Weeks View](https://user-images.githubusercontent.com/14041522/132008405-b7b0f6ac-9cb8-43db-b80f-22117bae582b.jpg)
![Week View](https://user-images.githubusercontent.com/14041522/132008411-ba178db2-2403-4f0b-a88b-b9c491091155.jpg)
![Day View + Agenda](https://user-images.githubusercontent.com/14041522/132008413-925a031e-8fc7-4984-9aad-875a975e81c4.jpg)

**Comment by N0ury** [comment]
Thanks @Offerel
