### ISSUE TITLE
caldavzap doesn't work. Nothing happens.

### ISSUE THREAD

**Issue by N0ury** [Offerel/roundcube_caldavzap#20]
Hi,

I'm trying to use caldavzap roundcube plugin with no success.
Here's what I have and what I did.

**1 - what I have:**

I have a Baikal caldav and carddav server.
It works fine under Apache, and used from MacOS and Android.
Url I use is: `https://baikal.dagami.org/cal.php/calendars/foo`
"`foo`" is my username without domain

I have a roundcube install that works fine.
**My username is foo@example.com** (same username but domain is included)

**2 - what I did:**

I have installed roundcube_caldavzap plugin in roundcube_root_directory
I have done this using git clone, and the renamed the dir to "caldavzap".
I have edited "config.inc.php":
// Domain for CalDAV server
$config['caldav_server'] = 'baikal.dagami.org';

// CalDAV Path where the DAV server resides
$config['caldav_path'] = '/cal.php/calendars/';

**What happens:**

When I run roundcube with Elastic skin:
In settings I see the option "calendars", and I can set the options and save them.
If I leave "settings" for going to "calendars", I get a blank screen with a top bar containing 3 buttons. "Calendars", "Todos" and "Refresh".
When I click one of these buttons, nothing happens, nothing goes to logs.
By "logs", I mean Apache logs (webmail ie roundcube, or baikal ie davcal).

When I run roundcube with "Classic" skin, It's the same for the options. But when I click to top button "Calendars" it's worst. I have a blank screen.

With "Larry" skin, it's the same as "Classic".

What can I do to debug this issue?
I'm a programmer but I don't know php.
If necessary, I can learn basic things for debugging purpose.

I need help to make caldavzap roundcube plugin work with my conf.

**Comment by Offerel** [comment]
Please have a look at the console if your browser. There should be error messages. I assume there is a login issue because you didn't use the same credentials for Roundcube and your DAV backend. Please make sure that the credentials are the same on both. Using only the name part is different from a complete email address.

Additionally make sure that your DAV backend is reachable in the same domain as your Roundcube install. Cross-Domain-Setups are not supported. The same rules as with Infcloud are involved here. If you absolutely must use Cross-Domain-Setup, make sure to send the correct headers with your request. Since there are a lot of different setup variants, I don't can assist you there. Please follow the instructions for your webserver in this case.

**Comment by N0ury** [comment]
Hi @Offerel 

Thanks for your fast reply.
1 - In order to avoid login issues, I have created a new baikal user (foo@dagami.org).
Now rouncube username and baikal one are the same.

login is anonimised.

2 - Baikal and roundcube use the same domain for this account.
I have other domains but I don't use them for this test. So no cross-domain issue.

3 - Javascript console displays **nothing** for `Classic` and `Larry` skins.
For `Elastic` skin I have errors.
a - when I click `Options`
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.min.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.bundle.min.js.map, line 0)
b - when I click `calendars`
Failed to load resource: the server responded with a status of 404 (Not Found)

There are no error messages in the logs.
Only a warning in the webmail (roundcube) log:
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/baikal/vendor/sabre/dav/lib/CalDAV/ICSExportPlugin.php on line 321

It looks like roundcube never tries to connect to baikal (my caldav server).

Maybe adding some "traces"?

**Comment by Offerel** [comment]
The error for the missing bootstrap files are from Roundcube itself. 

For the 404 error,  when you click on "calendar ", I assume that the calendar can't be found on the location where you have configured it. I have no idea how your infrastructure is setup. If you use `https://baikal.dagami.org/cal.php/calendars/foo` for baikal but `https://roundcube.dagami.org/` for Roundcube,  than this is indeed a Cross-Domain-Setup which will mostly not work. If Roundcube is on `https://baikal.dagami.org/rouncube/`, you should  set `$config['caldav_path'] = '/cal.php/calendars/';`

**Comment by N0ury** [comment]
Thanks @Offerel 

I have changed my conf.

My calendars are accessed here:
`https://cloud.dagami.org/cal.php/calendars/foo@dagami.org`
In this url there are three calendars.

Roundcube is here:
`https://cloud.dagami.org/roundcube`

and caldavzap is here:
`https://cloud.dagami.org/roundcube/?_task=caldavzap`

In config.inc.php I have:
```
$config['caldav_server'] = 'cloud.dagami.org';
$config['caldav_path'] = '/cal.php/calendars';
```

It still doesn't work with roundcube and there are no errors. Neither in Apache logs, nor in javascript console.
- roundcube works fine (except the caldavzap plugin)
- calendar is usable in browser and in MacOS client

It's difficult to debug something that doesn't work but has no error messages.

Any idea where to search?

**Comment by Offerel** [comment]
Please try to add a slash at the end of `$config['caldav_path'] = '/cal.php/calendars';` so that it becomes `$config['caldav_path'] = '/cal.php/calendars/';`. I didn't use Apache as webserver, because it's a little bit buggy and uses more resources as needed for most use cases. But im sure, there is somewhere a 404 error message in one of its logfiles, if it can't find a resource. If there is a login error, this should be also visible in the Apache logfiles. At least it is in both cases for NGinx and lighthttp. 

Personally, im using SabreDAV as a DAV resource. If im right, baikal is based on SabreDAV, but it's a little bit outdated since there is no active development for baikal. So, my setup is at least basically like yours. The only difference is that i rewrite cal.php to more readable url, to avoid naming resolution conflicts with some backends. So, my DAV resource's are located at a url like 

`https://mycloud.mydomain.com/dav/calendars/` or `https://mycloud.mydomain.com/dav/contacts/` or `https://mycloud.mydomain.com/dav/files/` and Roundcube is on `https://mycloud.mydomain.com/roundcube/`. In this case my config.php reads:

```
$config['caldavzap_url'] = 'plugins/caldavzap/caldavzap_0.13.2/roundcube.html';
$config['caldav_server'] = 'mycloud.mydomain.com';
$config['caldav_path'] = '/dav/calendars/';
```

> If a resource can't be found (for example, when you have set `$config['caldav_path'] = '/cal.php/calendars';` instead of `$config['caldav_path'] = '/cal.php/calendars/';`) you should see a 404 error in your browers webconsole and in the error log of your webserver)

**Comment by N0ury** [comment]
Thanks @Offerel but still nothing.

There's something new:
If I go to https://cloud.dagami.org/roundcube/plugins/caldavzap/caldavzap_0.13.2/index.html
I get a login page in german. If I go on and type my username and password, I can see all my calendars and todos with german labels.
I have tried to go to https://cloud.dagami.org/roundcube/plugins/caldavzap/caldavzap_0.13.2/roundcube.html but of course I get a lot of error messages.

Does this help in any way?

I was testing with Chrome and Safari.
I have tried with Firefox.
I have a 404 error:

GET https://cloud.dagami.org/skins/elastic/caldavzap.min.css  [HTTP/1.1 404 Not Found 174ms]

The file exists in <roundcube-root>/plugins/caldavzap/skins/elastic/caldavzap.min.css
In fact it exists for the three skins.
Is this the reason why it doesn't work?

**Comment by Offerel** [comment]
You can ignore https://cloud.dagami.org/roundcube/plugins/caldavzap/caldavzap_0.13.2/index.html. This is the standard CalDavZap login page. This isn't configured by Roundcube. Opening https://cloud.dagami.org/roundcube/plugins/caldavzap/caldavzap_0.13.2/roundcube.html is the right page, but opening it manually will not work, because all the information from Roundcube is not available when you open it manually. 

If you receive a 404 for https://cloud.dagami.org/skins/elastic/caldavzap.min.css this is true. No such resource exists or better, not at this location. Something seems to be misconfigured either in your Roundcube installation or for the Plugin, because the correct URL is build by the plugin automatically and should be https://cloud.dagami.org/roundcube/plugins/skins/elastic/caldavzap.min.css. You get this error when you open manually some resource.

One hint from my side: If you make changes to your config.php file (especially when you change paths), you should carefully clear your cache afterwards. CalDavZap is some JavaScript which is cached in the browser. Since you change the configuration at a other level (at the server not locally), the *.js files didn't change, and the browser loads the old files with the old configuration. The new configuration is loaded in some configurations only from scratch when no cached variant exists.

**Comment by N0ury** [comment]
This is a big step ahead.
As I didn't find why it doesn't work, I have reinstalled roundcube in the "traditionnal" way.
I didn't say that I'm On Debian Linux, and I use Debian packages.
On Debian, here's how roundcube is installed:
roundcube root dir is **`/var/lib/roundcube`**

It's content is:
```
config -> /etc/roundcube
index.php -> /usr/share/roundcube/index.php
logs -> ../../log/roundcube      
plugins
program -> /usr/share/roundcube/program
public_html
skins
temp
```

As you can see config files are in **`/etc/roundcube`**. Here's its content:
```
apache.conf 
config.inc.php
debian-db.php 
debian-db-roundcube.php       
defaults.inc.php
htaccess
lighttpd.conf 
mimetypes.php 
plugins
```

plugins are configured under this plugins directory

Furthermore `/var/lib/roundcube/plugins` directory contains only **links to /usr/share/roundcube/plugins files**.

So for caldavzap plugin, I have:
- installed the plugin in /usr/share/roundcube/plugins files
- added a link in /var/lib/roundcube/plugins to the real plugin in /usr/share/roundcube/plugins
- added a caldavzap dir in /etc/roundcube, and put the conf file there.

Note that I've done exactly the same with rcmcarddav plugin which works fine.

In order to have a clean Debian install, updates and upgrades, I would like to use Debian packages.

So I would like to know if there's a way to edit caldavzap plugin to make it work with a Debian install?

**Comment by Offerel** [comment]
I would not necessarily call this a "traditional way". I also use Debian and partly Arch Linux, but I never had the idea to use the Roundcube Debian package. Apparently, this way has its own quirks that are not part of the standard. I would always recommend installing Roundcube manually. I personally prefer the variant via Github Fullpackage. The packages via Debian do not have to correspond to what is recommended in the Fullpackage of GitHub. Often the Debian packages are also outdated or use obscure paths, as seen in the example. It also matters how the folders are configured by the webserver. Unfortunately, I can't say which symlinks need to be adjusted in this case, that's far beyond the support I can give. To me it looks like either the local or global configuration of the plugin is not found, or it points to wrong folders/symlinks.

**Comment by Offerel** [comment]
closed, since there is no response
