### ISSUE TITLE
Make Todos as one of default views

### ISSUE THREAD

**Issue by haoyu30** [Offerel/roundcube_caldavzap#22]
Hi. Thanks for this wonderful plugin. May I have a request? Can you add Todos as one of default views in configuration? The reason is that I find the Todos is more important when I check what I should do today. Thanks
Howard

**Comment by Offerel** [comment]
This should be possible. I will check it during the weekend.

**Comment by haoyu30** [comment]
Thanks. Also report that the choice of default view in preferences in RC 1.5.0 is not working . The default view always stays the initial view when caldavzap is installed.

**Comment by Offerel** [comment]
I have found a way to make your request work, or at least partially. I added "Todo" in the view settings and could switch with this to the ToDo's initially, but since this is only a small hack, it is overwritten 2 seconds later by the calendar default view. So this isnt working as of now. I have written an email to the developer of CalDavZap in hope he can assist me to find a better way.

For your other request, i tested it in my environment with RC 1.5.x. It is working as expected. However, sometimes the browser remember an old setting from within the cache and refuses to use the new setting. Please make sure, that the browser does not load an old setting from the cache.

**Comment by Offerel** [comment]
I have pushed a new commit [7a1b513](https://github.com/Offerel/roundcube_caldavzap/commit/7a1b513100466b188a2bdb07a79eae38ea7da395) in to the dev branch. This adds in the views a "Todo" view. At least here with RC 1.5 final, this works as expected.

If this is what you want, please drop me some info and i will make a new release.

BTW: In the dev branch a caching service worker is added. In theory this should preload all the assets and should make subsequent calls a little bit faster. If you use propertystorage object on your DAV server in principal storage, most of the settings are saved there and will overwrite most of the time all other settings. If thats the case on your side, be sure to clear the cache and also the propertystorage object for your account.

**Comment by haoyu30** [comment]
Thanks. After updating, I was able to switch to Todo view with another account. My own account still stays the same and I cannot change to any other view. Strangely, this Todo view is different from the real one (after click the todo icon). It have four month mini windows on top and filters, action and complete. All action items are not there. 
Might need to update localization to add todo menu.
Thanks

**Comment by Offerel** [comment]
That's strange. Can you please check if you have some settings saved in propertystorage at the CalDAV server? If so, maybe removing this settings should help. In my case, I use SabreDAV as backend. There is a table 'propertystorage' which should hold these settings in JSON like structure. This settings take always precedence over all other settings and will overwrite them.

Many thx for the hint with the language files, I have updated them now.

**Comment by Offerel** [comment]
I have rechecked my local variant and the one from GIT. There is no visual difference in the view. I have checked at least Larry and Elastic Skin. Ther month mini is visible with both themes and no matter, if i click the ToDo icon or using the setting change. How many mini months are visible depends on how big your resolution/monito is. In my case, i have 6 months, but if you have a smaller screen, there could be also 2 months or only the actual month. Action and complete filters are also visible in all these states. Im not sure what you mean with action items. If you mean the buttons to change between calendear, todo and refresh, these buttons are at the top for elastic skin and at the left with larry theme/skin. 

Classic skin is no longer supported. Maybe it works, but since this no longer actively supported by Roundcube i didn't support it actively.

For me, your issue sounds like a caching issue or maybe some javascript has a error and refuses to load some stylesheets later (after the error). You can try to force load without the cache, or with a private session (aka porn mode) within your browser. Please try to keep the browser console open (F12) and watch out for javascript errors. Please disable Browser extensions, maybe they block something or change requests. I hope this is not the case, but nobody knows for sure.

BTW: I tested in Firefox and Ungoogled-Chromium so far. So it should be fine for most of the browser configurations.

**Comment by haoyu30** [comment]
You are right. It is cache issue. If using firefox on Debian, Todos view shows up as the default view. Microsof's Edge is OK. It is windows's chrome that is not honoring settings. When I did cache clean, the standard settings are not good. I have to choose "Hosted app data" to do the trick. Now it seems working fine. 
Thanks a lot for this updating.

**Comment by Offerel** [comment]
Fixed with #24 

I have made a new release with the latest changes.

**Comment by Offerel** [comment]
In my last commit on dev branch, I have added an option to ignore hopefully server settings, coming from propertystorage. I have no idea, if this helps but maybe you can try if this suites better your needs.

**Comment by Offerel** [comment]
I have found a better way to prefer Roundcube values instead of the propertystorage. I will still leave the option to completely ignore propertystorage in but with the new commit it should no longer be necessary
