### ISSUE TITLE
Changing Language

### ISSUE THREAD

**Issue by luehm** [Offerel/roundcube_caldavzap#6]
Hi Offerel!
Thanks for porting this to RoundCube - you've done a fantastic job. I'm trying to change the interface language in the config_rc.js and config.js (from de_DE to en_US). I know that you've only ported this app, however do you have any suggestions? Simply changing the variable value does not seem to have an effect.

**Comment by Offerel** [comment]
You should change `var globalInterfaceCustomLanguages=['en_US'];` and `var globalInterfaceLanguage='en_US';` in config_rc.js. However, this is a good point. I will try to change that automatically from within Roundcube, so that it uses the Roundcube language and en_US as fallback,

If the above change do not work immediately, try to clear the browser cache. CalDAVZap uses cache a lot and very aggressive.

**Comment by Offerel** [comment]
I have made now locally some additions, so that changing the language in Roundcube, also changes the language in CalDAVZap. That new function uses a cookie, so cookies must be allowed at least for the current domain. If the user changes the RC language to a language not supported by CalDAVZap, it falls back to en_US. Currently only the language is changed, but not the values for WeekendDays and FirstDayOfWeek. Date and time formats are based automatically on the language code. 

I hope i can change the timezone info in the same way. I try to make a commit today with that changes.  If that's done you can check out and report if it works for you and if you find some problems. If all is fine, i make a new release.

**Comment by Offerel** [comment]
You can now checkout the last commit and test it.

**Comment by luehm** [comment]
Sorry, read your emails but never responded. Worked a treat. Thanks for all your work!
