### ISSUE TITLE
where it make configuration changes for week format

### ISSUE THREAD

**Issue by henrythemouse** [Offerel/roundcube_caldavzap#9]
I'd like to have the date picker as well as the calendar show the weeks starting on Sunday. Currently they both start on Monday. I read in one of the other issues that config_rc.js is a file that can be used to make some changes. So, to test that I changed:

`var globalDatepickerFirstDayOfWeek=1 to read:;
var globalDatepickerFirstDayOfWeek=0;`

Then I ran the config_update.sh  script to update the cache, cleaned out my browser cache and restarted roundcube. Still the datepicker started the week on Monday.

Would it be safe to make changes in config.js? I see some mention of these variables being automatically set and I don't want to mess up the config accidently.

TIA

**Comment by Offerel** [comment]
I can put that as a variable in the plugin config if you want. You are right, currently it exists only on the upstream level as a parameter. Currently it should be changed in `config_rc.js` file since this file overwrites the default values of `config.js`.

Using config_update.sh didn't reset the cache in my case to. But you can change the digit `#V 20171211111240` in `cache.manifest` to a other value manually or exclude the link to this file in roundcube.html with `<!-- <html lang="en" manifest="cache.manifest"> -->`. The last variant disables caching  completely, the first variant resets the cache.

I try to make it as a config parameter in roundcube today and update this issue, if its done.

**Comment by henrythemouse** [comment]
I made the local change in config_rc.js and it's working. Can you tell me what the config_rc.min.js file is for (not to mention all the other *min* files)?

Thanks

**Comment by Offerel** [comment]
all min files are only compressed versions of the normal files. If both files are there, always the min version should be loaded automatically by my scripts. This should save a little bit bandwidth and load faster.

I have now a dev version of this plugin, where some options are loaded dynamically. For this options a settings page is available in the standard RC settings. This are primary your options from this feature request and some others. This configs are saved on per user base, not globally. However since i found a small bug in the plugin, i will first fix that bug, before i make a new release.

**Comment by Offerel** [comment]
I have made a new version 1.5.0. You can now specify some options from a settings page inside of RC preferences. The same options are also available in config.inc.php. The options set inside of RC take precedence over the default ones in config.inc.php and can differ from that settings. However they are only saved for the specific user.

**Comment by henrythemouse** [comment]
Very nice, thanks.
